import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/ui/accueil/navBar/NavBar";
import Footer from "@/app/ui/accueil/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jarry Bérénice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <header className="w-full flex-none">
          <NavBar />
        </header>

        <main className="flex-grow p-6 ">{children}</main>

        <footer className="w-full flex-none ">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
